project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 ML Fundamentals"
            file: content/01_journal/01_ML_Fundamentals.qmd
          - text: "02 Supervised ML"
            file: content/01_journal/02_Supervised_ML.qmd
          - text: "03 Automated Machine Learning with H20"
            file: content/01_journal/03_Automated_ML_H20.qmd
          - text: "04 Performance Measures"
            file: content/01_journal/04_Performance_Measures.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd
format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto